# Server Configuration
server.port=8080
server.servlet.session.timeout=30m
server.servlet.session.cookie.name=JSESSIONID

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Firebase Configuration (Ensure your JSON file is in the root or resources)
# Replace with your actual JSON file name if different
firebase.config.path=serviceAccountKey.json

# File Upload Limit (for product images)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging for Debugging
logging.level.org.springframework.web=INFO
logging.level.com.mobilestore.Abdulbasit=DEBUG

logging.level.org.springframework.web.servlet.PageNotFound=DEBUG

# Email Configuration (Gmail SMTP)
# Brevo SMTP Configuration

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587

spring.mail.username=aaf1ed001@smtp-brevo.com
spring.mail.password=HLcFIXZxPTRp6vaf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
